name: pre-commit-with-autofix
description: "Run pre-commit with autofix"
runs:
  using: composite
  steps:
    - name: Set up Git repository
      uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
    - name: Cache pre-commit
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit/
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
    - id: pre-commit
      name: Run pre-commit
      run: uvx --with pre-commit-uv pre-commit run --show-diff-on-failure --color=always -a
      continue-on-error: true
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: "style: apply pre-commit fixes"
      if: github.event_name == 'pull_request' && steps.pre-commit.outcome != 'success'
    - run: echo pre-commit failed; exit 1
      if: steps.pre-commit.outcome != 'success'
      shell: bash
